import { useState } from "react";
import { ArrowRight, CalendarDays, ChevronLeft, Clock3, Gift, LogOut, Phone, UserRound } from "lucide-react";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";

export default function Account() {
  const { user, isAuthenticated, loading, logout } = useAuth();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const bookingsQuery = trpc.bookings.mine.useQuery(undefined, { enabled: isAuthenticated, retry: false });

  if (loading) return <main dir="rtl" className="account-page flex min-h-screen items-center justify-center">جارٍ تحميل حسابك…</main>;

  if (!isAuthenticated) {
    return <main dir="rtl" className="account-page min-h-screen px-4 py-8 sm:py-16"><div className="mx-auto max-w-md"><a href="/" className="account-back-link"><ArrowRight size={17} /> العودة للرئيسية</a><div className="account-card mt-8"><div className="account-logo"><UserRound size={25} /></div><h1 className="mt-6 text-3xl font-black text-[#073b63]">مرحباً بعودتك</h1><p className="mt-2 leading-7 text-[#708695]">ادخل لحسابك باش تشوف حجوزاتك ونقاط وفائك</p><form className="mt-8 space-y-4" onSubmit={event => { event.preventDefault(); startLogin(); }}><label className="account-label">البريد الإلكتروني<input type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="name@example.com" autoComplete="email" required /></label><label className="account-label">كلمة السر<input type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="••••••••" autoComplete="current-password" required /></label><Button type="submit" className="mt-3 h-12 w-full rounded-full bg-[#073b63] text-base font-black hover:bg-[#0b527f]">دخول</Button></form><button type="button" onClick={startLogin} className="mt-5 w-full text-center text-sm font-black text-[#1397a5] hover:text-[#073b63]">ما عندكش حساب؟ أنشئ واحداً</button><p className="mt-8 border-t border-[#edf3f4] pt-5 text-center text-xs leading-6 text-[#8a9da6]">تقدر تحجز حتى بلا حساب عبر الاتصال على <a href="tel:+213555000000" dir="ltr" className="phone-number font-black text-[#073b63]">0555 00 00 00</a></p></div></div></main>;
  }

  const bookings = bookingsQuery.data?.bookings ?? [];
  const points = bookingsQuery.data?.loyaltyPoints ?? 0;
  return <main dir="rtl" className="account-page min-h-screen px-4 py-8 sm:py-14"><div className="mx-auto max-w-4xl"><div className="flex flex-wrap items-center justify-between gap-4"><a href="/" className="account-back-link"><ArrowRight size={17} /> العودة للرئيسية</a><Button variant="outline" onClick={() => void logout()} className="rounded-full border-[#d5e6e9] font-bold text-[#073b63]"><LogOut size={16} /> تسجيل الخروج</Button></div><div className="mt-8 flex flex-wrap items-end justify-between gap-4"><div><p className="section-kicker">مساحتك الخاصة</p><h1 className="mt-2 text-3xl font-black text-[#073b63]">حسابي وحجوزاتي</h1><p className="mt-2 text-[#708695]">مرحباً {user?.name || user?.email || "بك"}</p></div><div className="points-card"><Gift size={23} /><div><span>نقاط وفائك</span><strong dir="ltr">{points} نقطة</strong></div></div></div><section className="account-card mt-8"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-black text-[#073b63]">سجل الحجوزات</h2><CalendarDays className="text-[#1397a5]" size={22} /></div>{bookingsQuery.isLoading ? <p className="py-12 text-center text-sm text-[#78909b]">جارٍ تحميل حجوزاتك…</p> : bookings.length === 0 ? <div className="empty-account-state"><CalendarDays size={32} /><p className="font-black">ما عندكش حجوزات حتى الآن</p><a href="/#top" className="text-sm font-black text-[#1397a5]">احجز أول غسلة</a></div> : <div className="mt-5 grid gap-3">{bookings.map(booking => <article key={booking.id} className="booking-history-row"><div><strong>{booking.service}</strong><div className="mt-1 flex flex-wrap gap-3 text-xs text-[#78909b]"><span><CalendarDays size={13} /> <b dir="ltr">{booking.bookingDate}</b></span><span><Clock3 size={13} /> {booking.bookingTime}</span></div></div><div className="text-left"><strong dir="ltr" className="text-[#073b63]">NQIHA-{String(booking.id).padStart(6, "0")}</strong><div className="mt-1 text-xs font-bold text-[#1397a5]">{booking.status === "completed" ? "مكتمل" : booking.status === "cancelled" ? "ملغى" : "قيد المعالجة"}</div></div></article>)}</div>}</section><div className="mt-5 flex items-center gap-3 rounded-2xl bg-[#eafafb] p-4 text-sm text-[#527183]"><Phone size={18} className="shrink-0 text-[#1397a5]" /><span>تحتاج مساعدة؟ <a href="tel:+213555000000" dir="ltr" className="phone-number font-black text-[#073b63]">0555 00 00 00</a></span><ChevronLeft className="mr-auto" size={17} /></div></div></main>;
}
