import { useState } from "react";
import { ArrowRight, CalendarDays, CheckCircle2, Clock3, MapPin, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

const labels = { pending: "قيد الانتظار", confirmed: "مؤكد", completed: "مكتمل", cancelled: "ملغى" } as const;
export default function Track() {
  const [reference, setReference] = useState("");
  const [submitted, setSubmitted] = useState("");
  const query = trpc.bookings.track.useQuery({ reference: submitted }, { enabled: Boolean(submitted), retry: false });
  return <main dir="rtl" className="account-page min-h-screen px-4 py-10 sm:py-20"><div className="mx-auto max-w-xl"><a href="/" className="account-back-link"><ArrowRight size={17} /> العودة للرئيسية</a><section className="account-card mt-8"><div className="account-logo"><Search size={25} /></div><h1 className="mt-6 text-3xl font-black text-[#073b63]">تتبع حجزي</h1><p className="mt-2 leading-7 text-[#708695]">اكتب الرقم المرجعي الموجود في رسالة تأكيد الحجز لمعرفة حالته.</p><form className="mt-8 flex gap-2" onSubmit={event => { event.preventDefault(); setSubmitted(reference.trim().toUpperCase()); }}><input dir="ltr" className="h-12 min-w-0 flex-1 rounded-full border border-[#dcebed] px-4 text-left font-black outline-none focus:border-[#35c3d0]" value={reference} onChange={event => setReference(event.target.value)} placeholder="NQIHA-090001" pattern="NQIHA-[0-9]{6}" required /><Button type="submit" className="h-12 rounded-full bg-[#073b63] px-5 font-black"><Search size={17} className="ml-2" /> بحث</Button></form>{query.isFetching && <p className="mt-6 text-center text-sm text-[#78909b]">جارٍ البحث…</p>}{query.error && <p role="alert" className="mt-6 text-center text-sm font-bold text-red-600">{query.error.message}</p>}{query.data && <article className="mt-6 rounded-2xl border border-[#bce8eb] bg-[#effbfc] p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs text-[#78909b]">الحالة</p><h2 className="mt-1 text-xl font-black text-[#073b63]">{labels[query.data.status]}</h2></div><CheckCircle2 className="text-[#1397a5]" size={30} /></div><div className="mt-5 grid gap-3 text-sm"><div className="flex items-center gap-2"><CalendarDays size={16} className="text-[#1397a5]" /><span dir="ltr">{query.data.bookingDate}</span></div><div className="flex items-center gap-2"><Clock3 size={16} className="text-[#1397a5]" />{query.data.bookingTime}</div><div className="flex items-start gap-2"><MapPin size={16} className="mt-1 text-[#1397a5]" />{query.data.address}</div><div className="border-t border-[#ccebed] pt-3 font-black">{query.data.service} · {query.data.totalPrice.toLocaleString()} دج</div></div></article>}</section></div></main>;
}
